services:
  server:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
#    develop:
#      watch:
#        - action: rebuild
#          path: .
  db:
    container_name: pgbd
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dayli
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=noemail@nomail.com
#      - PGADMIN_DEFAULT_PASSWORD=123qwe
#    ports:
#      - "8080:80"
#    volumes:
#      - ./data/pgadmin:/var/lib/pgadmin
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt

